#ifndef COMMONS_ERROR_CODES_H_
#define COMMONS_ERROR_CODES_H_


#define ERROR_NO_RESOURCES -1
#define ERROR_FILE_DOES_NOT_EXIST -2
#define ERROR_FILE_NO_READ_PERMISION -3
#define ERROR_FILE_NO_WRITE_PERMISION -4
#define ERROR_MEMORY -5
#define ERROR_CONSOLE_DISCONNECTED -6
#define ERROR_CONSOLE_FINISH_COMMAND -7
#define ERROR_ALLOC_BIGGER_THAN_PAGE_SIZE -8
#define ERROR_NO_PAGES_FOR_PROCESS -9
#define ERROR_FILE_BAD_DELETE -10
#define ERROR_FD_DOES_NOT_EXIST -11
#define ERROR_FILE_CREATE_PERMISION -12
#define ERROR_FS_OPERATION -13
#define ERROR_SEM_DOES_NOT_EXIST -14
#define ERROR_SHARED_VAR_DOES_NOT_EXIST -15
#define ERROR_CPU_DISCONNECTED -16
#define INTERRUPT_KERNEL_CONSOLE -17
#define ERROR_MEMORY_DISCONNECTED -21
#define ERROR_UNDEFINED -20

#endif /* COMMONS_ERROR_CODES_H_ */
